# Taps
tap "homebrew/bundle"
tap "homebrew/services"

# Homebrew
brew "direnv"
brew "git"
brew "jq"
brew "swiftformat"
brew "tailscale"
brew "wget"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "atuin"
brew "starship"
brew "emacs"
brew "gh"

if OS.mac?
brew "finestructure/tap/arena"
brew "mas"

# Cask
cask "raycast"
cask "visual-studio-code"
cask "docker"
cask "discord"
cask "slack"
cask "spotify"

# Mac App Store
mas "iA Writer", id: 775737590
mas "Tailscale", id: 1475387142
mas "1Password 7", id: 1333542190
mas "SQLiteFlow", id: 1378587993
mas "Ivory", id: 6444602274
mas "Pixelmator Pro", id: 1289583905
end
