# Might want to get this font: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Meslo.zip

format = """$directory$character"""

right_format = """
$swift$git_branch$all"""

# Disable the blank line at the start of the prompt
add_newline = false

[hostname]
ssh_symbol = "\uf233"
format = '[$ssh_symbol$hostname]($style)'

[os]
disabled = false

[os.symbols]
Macos = "\ue711"
Ubuntu = " \uf31b"

[git_metrics]
disabled = false

[line_break]
disabled = true

[git_status]
disabled = true

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"
vimcmd_symbol = "[<](bold green)"

[directory]
truncate_to_repo = false
read_only = " ro"

[swift]
format = "\ue755 "
detect_files = ['Package.swift', '.swiftformat']
