# Might want to get this font: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Meslo.zip

format = """$directory$character"""

right_format = """
$swift$git_branch$git_status$all"""

# Disable the blank line at the start of the prompt
add_newline = false

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"
vimcmd_symbol = "[<](bold green)"

[directory]
truncate_to_repo = false
read_only = " ro"

[swift]
format = "\ue755 "
detect_files = ['Package.swift', '.swiftformat']
